### ISSUE TITLE
Topologies with coordinates are not considered the first frame

### ISSUE THREAD

**Issue by RasmusFonseca** [getcontacts/getcontacts#14]
Currently if a pdb file is used as topology, the coordinates of the pdb file are ignored. This is different from what happens when you load molecules in vmd. Is this behavior desired?

For my openmm trajectories the topology pdb-file precedes the equilibration so I'd prefer to leave it out of the contact analysis (at least by default).

**Comment by RasmusFonseca** [comment]
I consider this resolved now. The code currently doesn't consider the topology a frame by itself. As such it behaves consistently across different topology formats, but it's not how VMD usually behaves. Any input?

**Comment by akma327** [comment]
I'd say we can close for now, unless many future users want to have the pdb included as the first frame. In our readme, we'll specify that this computes contacts in trajectory. Users that want contacts in pdb can just run static_contacts.py for now.

**Comment by RasmusFonseca** [comment]
:+1:
