### ISSUE TITLE
Need a way to convert from atom to residue resolution contacts

### ISSUE THREAD

**Issue by akma327** [getcontacts/getcontacts#17]

**Comment by RasmusFonseca** [comment]
Where? This would work if you're ok with a bash solution:
```bash
cat contactfile.tsv | sed -e 's/\(.:...:[0-9]*\):[^[:space:]]*/\1/g'
```

**Comment by akma327** [comment]
Perhaps, users should be allowed to denote a flag that would output as residue resolution? Default would be atomic.

**Comment by akma327** [comment]
Is there a command that would allow you to eliminate duplicates that are A--B and B--A?
For example, after abstracting away the atom level information to residue level, the first and third line should be combined to just one. 

27491	hbbb	A:THR:49	A:THR:58
27491	hbbb	A:ASP:51	A:THR:56
27491	hbbb	A:THR:58	A:THR:49

**Comment by RasmusFonseca** [comment]
```
$ grep "#" > res_contacts.tsv
$ grep -v "#" contactfile.tsv | sed -e 's/\(.:...:[0-9]*\):[^[:space:]]*/\1/g' | awk ' { if ($4 < $3){t = $3; $3 = $4; $4 = t }; print; } ' | tr ' ' '\t' | sort | uniq >> res_contacts.tsv
```

**Comment by RasmusFonseca** [comment]
A bit of explanation. The `contactfile.tsv` above is the first 10 lines of the system in the `example` folder, except the first "sb" interaction has been duplicated and had the atoms reversed (so it should disappear). You'll see in the `res_contacts.tsv` that only the "76-82" version, not the "82-76" version, has been retained. 

To break down the second line above:
* The `grep` command filters away the comment (already added in the first line)
* The `sed` command strips the atom name information
* The `awk` command swaps rows 3 and 4 if the contents of row 4 < contents of row 3
* Unfortunately that converts tabs to spaces, so the `tr` command converts them back to tabs again
* The `sort | uniq` combo ensures that no duplicate lines exist. If, for debugging purposes, you'd want to know which lines were duplicated you could add `-d` to the `uniq command` and it would tell you which appeared twice:
```
$ grep -v "#" contactfile.tsv | \
  sed -e 's/\(.:...:[0-9]*\):[^[:space:]]*/\1/g' | \
  awk ' { if ($4 < $3){t = $3; $3 = $4; $4 = t }; print; } ' | \
  tr ' ' '\t' | \
  sort | uniq -d > res_contact_duplicates.tsv
$ cat res_contact_duplicates.tsv
0	sb	A:ARG:76	A:GLU:82
0	vdw	A:GLU:11	A:GLU:11
```

**Comment by akma327** [comment]
Hmm, there seems to be something going off on larger files. This is tail of a 28000 frame simulation.

999	hbss	A:ASP:27	A:THR:30
999	hbss	A:GLU:61	A:LYS:9
999	sb	A:GLU:61	A:LYS:9
99	hbbb	A:ILE:12	A:THR:20
99	hbbb	A:LEU:10	A:THR:22
99	hbbb	A:LEU:14	A:THR:18
99	hbsb	A:GLN:37	A:GLY:43
99	hbss	A:GLN:37	A:TYR:21
9	hbbb	A:ILE:12	A:THR:20
9	hbbb	A:LEU:14	A:THR:18
9	hbbb	A:THR:30	A:VAL:11
9	hbsb	A:ASP:6	A:THR:7
9	sb	A:GLU:32	A:LYS:36

**Comment by RasmusFonseca** [comment]
Things are moving along a bit. There's now a `contact_calc.transformations.res_contacts` function that performs this computation. Do we need an executable that wraps this function? What was the application for this question?
