### ISSUE TITLE
vdw atomic radii for non-standard atom types

### ISSUE THREAD

**Issue by RasmusFonseca** [getcontacts/getcontacts#21]
Currently the program crashes when computing vdw interactions for atoms whose residue name does not start with either `['H', 'C', 'N', 'O', 'S', 'P']`. The vdw computation assumes the first letter of the residue name indicates the element. Theres a number of problems with this:

1. Some common elements, like potassium 'K' aren't recognized and we don't fall back to a default atomic radius
2. Some common elements, like chlorine 'Cl', will get mistaken for carbon. 
3. Output from some modeling tools will have numbers in the beginning of the atom name. It'd be better to rely primarily on the element column and then fall back on the first alphabetic (non-digit) character of the name if the element is not defined. 

For now I'll fix the crashing by defaulting to carbon radii, but this is a hack that needs to be fixed

**Comment by RasmusFonseca** [comment]
I think it's the 5xnd example that has a couple of Cl ions.

**Comment by akma327** [comment]
van der waals should be able to differentiate the edge case of CA calcium vs CA alpha carbon since resname for calcium is CA whereas it would be a residue for alpha carbon. I also added in all the biologically relevant ions to be thorough.

Will close issue for now.
