### ISSUE TITLE
Command on webpage is wrong (on tutorial for analysis of md simulations)

### ISSUE THREAD

**Issue by fatipardo** [getcontacts/getcontacts#27]
The website reads:
get_contact_frequencies.py --input_files contacts_1.tsv -all --output_file resfrequencies_1.tsv
Should be changed to:
get_contact_frequencies.py --input_files contacts_1.tsv --itypes all --output_file resfrequencies_1.tsv

Same problem as before, but in the section for dynamic contacts

**Comment by RasmusFonseca** [comment]
Ok I've tried search-and-replacing now and hopefully this was the last one.
