### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by jkaindl** [getcontacts/getcontacts#30]
In the README.md file  the commad is given as:

dynamic_contacts.py --topology my_top.psf ...

while the dynamic_contact is started by

get_dynamic_contacts.py --topology my_top.psf ...

Thanks

**Comment by RasmusFonseca** [comment]
Thank you! We've gone through some renaming. I fixed
* `dynamic_contacts -> get_dynamic_contacts`
* `MDContacts -> GetContacts`
* Interaction types parameter: `-hb -vdw -sb  =>  --itypes hb vdw sb`

Sorry if this caused confusion
