### ISSUE TITLE
group selection 

### ISSUE THREAD

**Issue by SiriCamee** [getcontacts/getcontacts#33]
Hi there,

It would be great if you could implement a tool in which you can select two regions of the protein system and calculate the the total or the number of hydrogen bonds or salt bridges between these two regions.

Thanks in advance!

Best,
Siri

**Comment by RasmusFonseca** [comment]
I agree this'd be a nice feature. There are multiple applications for this such as interface-interface analysis or protein-ligand interactions etc. The default behavior when not specifying selection2 could be our current behavior.

**Comment by akma327** [comment]
@SiriCamee Just added an implementation where you can specify two atom selections (ie --sele "chain A" --sele2 "chain B") to compute interactions between the two groups. Feel free to give it a try and let us know how it does. Any feedback would be greatly appreciated.
