### ISSUE TITLE
get_contact_fingerprint.py - csv instead of tsv as tabel output

### ISSUE THREAD

**Issue by jkaindl** [getcontacts/getcontacts#35]
I used the table_output flag of get_contact_fingerprints.py. According to the help message one is supposed to get a tsv-file

--table_output TABLE_OUTPUT
                        If specified, the tab-separated frequency table will be written to this file

However, I ended up with a csv-file^^
Thanks

**Comment by RasmusFonseca** [comment]
Thanks again! I think excel gave me trouble at some point with tab-separated files, but right now it seems to work, so we're going with tab-separated for consistency.
