### ISSUE TITLE
contact_consumer method in compute_contacts.py for writing out contacts seems to have issues on smaller outputs. 

### ISSUE THREAD

**Issue by akma327** [getcontacts/getcontacts#38]
Currently getting no output when running pi_stacking computation for a small atom selection. Traced the code and see that the contacts array is populated with the appropriate contacts in 
def contact_consumer(), but first_contact_frame is assigned to 90, whereas waiting_for_frame is assigned to beg = 0. Never enters the while waiting_for_frame == first_contact_frame: loop to write out the contacts.

**Comment by RasmusFonseca** [comment]
Ill start checking this. It'd be awesome if there was a small test-case that covers this (see e.g. https://github.com/getcontacts/getcontacts/blob/master/tests/test_get_dynamic_contacts.py)

**Comment by akma327** [comment]
Thanks @RasmusFonseca. 
So the bug seems to occur whenever there is no contacts in the first frame (ie frame 0). If you go to the example folder with 5xnd, here's an example case where the bug occurs. 

traj="5xnd_trajectory.dcd"
top="5xnd_topology.pdb"
output="sb.tsv"
python get_dynamic_contacts.py --trajectory $traj --topology $top --output $output --itypes sb --sele "resname ASP LYS"

**Comment by RasmusFonseca** [comment]
I added a test for this case that you can run from the root of the repo:
```
MBPro:~/Documents/getcontacts $ pytest tests/test_get_dynamic_contacts.py
```

It fails right now as the default "--sele" argument makes the program fail. @akma327 Could you fix it so the program works again when "--sele" is not given on the commandline.

**Comment by akma327** [comment]
Hmm, I believe I found/corrected the bug that was causing the issue, but still not passing the most recent test you added. I ran the test_empty_frame unittest with the following command locally and it works for me:

traj="5xnd_trajectory.dcd"
top="5xnd_topology.pdb"
output="5xnd_contacts.tsv"
python get_dynamic_contacts.py --trajectory $traj --topology $top --output $output --itypes sb --sele 'resname ASP LYS'

Can you double check that the syntax for argv (line 55 test_get_dynamic_contacts.py) matches the command I used above?

**Comment by akma327** [comment]
looks like we have a clean build now, thanks @RasmusFonseca
