### ISSUE TITLE
Setting --hbond_cutoff_ang 180 causes intra-residue hbonds

### ISSUE THREAD

**Issue by RasmusFonseca** [getcontacts/getcontacts#39]
When setting `--hbond_cutoff_ang 180` hbonds are created between the nitrogens in arginine for example.

**Comment by akma327** [comment]
I dont recall ever imposing a restriction against intra-residue interactions? We can always impose a similar restriction as we did for vdw (having at least x residues apart)

**Comment by RasmusFonseca** [comment]
Hm, I guess there are examples where it makes sense, e.g. sidechain - main chain hbonds. The triangle on ARG sidechain looks a little crazy though. Having a min-residue distance that defaults to 1 for hbonds would probably be good.

**Comment by akma327** [comment]
Added the --hbond_res_diff argument, defaults to 1 for static structures to avoid intraresidue interactions, and 0 for simulations (since the angle criteria takes care of intraresidues and dont want additional filters to slow down the pipeline).
