### ISSUE TITLE
Efficient selection filter

### ISSUE THREAD

**Issue by RasmusFonseca** [getcontacts/getcontacts#40]
Currently selections are supported by a VMD-selection that gets converted into a list here:

https://github.com/getcontacts/getcontacts/blob/05ebe6b049f5dd28a743319a6b4c426cb20808b7/contact_calc/contact_utils.py#L126

These lists are then passed into `compute_frame_contacts` and further into the interaction-specific methods and used in the inner-most loops to filter based on selections, e.g.:

https://github.com/getcontacts/getcontacts/blob/05ebe6b049f5dd28a743319a6b4c426cb20808b7/contact_calc/vanderwaals.py#L64-L65

If there are a lot of atoms in the selection-list, then I'd expect these four inclusion checks to be very time-consuming, and to make it worse they're called for every pair of potentially interacting atoms. I'd like to suggest a number of speedups, but would like your opinion first as I'm not completely sure if it will mess with other functionality:

1. Move the [conversion from VMD-selection string to atom list](https://github.com/getcontacts/getcontacts/blob/05ebe6b049f5dd28a743319a6b4c426cb20808b7/contact_calc/compute_contacts.py#L198-L202) out of `compute_fragment_contacts` and into `compute_contacts`, so the conversion only happens once, and not for every fragment.
2. In `get_atom_selection_labels` change the `list` to a `set` which has significantly faster lookup. 
3. In `filter_dual_selection_vdw` introduce temporary variables so inclusion checks are only performed 2 times not 4 (this I think should be fine .. just mentioning it as part of the optimization). 
4. Change the values of `sele1_atoms` and `sele2_atoms` from strings to integers. I don't think they're used for anything other than checking for selection inclusion, and comparing two integers is much faster than comparing two strings.

**Comment by akma327** [comment]
Yes, indeed the dual selection filter will need optimizing to be computationally tractable for larger systems. I've gotten started on the list to set conversion, hence now with dual selection it is O(1) rather than O(n), and should be comparable run time to having default of no dual filter (which uses index_to_label dictionary).

**Comment by akma327** [comment]
Will close this for now, but feel free to open again for further optimizations (ie cython, identifying other bottlenecks)
