### ISSUE TITLE
contact_utils.py error

### ISSUE THREAD

**Issue by fatipardo** [getcontacts/getcontacts#54]
I just installed get_contacts in MacOS. I was trying to run the example suggested and got an error message. 

input: get_dynamic_contacts.py --topology 5xnd_topology.pdb --trajectory 5xnd_trajectory.dcd --itypes all --output 5xnd_all-contacts.tsv 

output:

Info) VMD for MACOSXX86_64, version 1.9.4a26 (March 13, 2019)
Info) http://www.ks.uiuc.edu/Research/vmd/
Info) Email questions and bug reports to vmd@ks.uiuc.edu
Info) Please include this reference in published work using VMD:
Info)    Humphrey, W., Dalke, A. and Schulten, K., `VMD - Visual
Info)    Molecular Dynamics', J. Molec. Graphics 1996, 14.1, 33-38.
Info) -------------------------------------------------------------
Info) Multithreading available, 8 CPUs detected.
all_atoms
Traceback (most recent call last):
  File "/Users/test_project_folder/getcontacts/get_dynamic_contacts.py", line 97, in <module>
    main()
  File "/Users/test_project_folder/getcontacts/get_dynamic_contacts.py", line 81, in main
    ligand, solv, lipid, sele1, sele2)
  File "/Users/test_project_folder/getcontacts/contact_calc/compute_contacts.py", line 222, in compute_contacts
    index_to_atom = gen_index_to_atom(top, traj)
  File "/Users/test_project_folder/getcontacts/contact_calc/contact_utils.py", line 237, in gen_index_to_atom
    chains, resnames, resids, names, elements, indices, icodes = get_atom_selection_properties("all_atoms")
ValueError: not enough values to unpack (expected 7, got 6)

####

I went to see the code of the function: get_atom_selection_properties("all_atoms") 
After printing the selections, I saw that the lists for chain, resnames, resids, etc, were empty, only the list of 'names' had values. I do not know why this is happening.

**Comment by RasmusFonseca** [comment]
There was recently made updates to vmd-python which we depend on. I'm still not sure what changed but will try to get a fix in by the weekend. FYI @ajvenkat

**Comment by fatipardo** [comment]
Thanks for pointing out to the problem. I then instead installed vmd-python v.2.0.10 (https://github.com/Eigenstate/vmd-python/releases/tag/v2.0.10) and now I can use getcontacts.
