### ISSUE TITLE
Counting salt-bridges of non-equal selections

### ISSUE THREAD

**Issue by Clownshift** [getcontacts/getcontacts#67]
I believe, that for non-equal selection, not all possible salt bridges are considered.
In [salt_bridges.py](https://github.com/getcontacts/getcontacts/blob/master/contact_calc/salt_bridges.py), lines 76 ff :

    contacts_12 = set(parse_contacts(evaltcl("measure contacts %f $s1anions $s2cations" % cutoff_dist)))

    if sele1 == sele2:

        contacts_21 = set([])

    else:
        contacts_21 = set(parse_contacts(evaltcl("measure contacts %f $s2cations $s1anions" % 
    cutoff_dist)))

If `sele1 != sele2` I think, you should check for `$s1cations $s2anions`. The way it is right now, to me, it looks as if you would look for the same contact pairs twice.

**Comment by RasmusFonseca** [comment]
I agree. Will double check to make sure and fix. Thanks!

**Comment by RasmusFonseca** [comment]
Verified. Thanks so much for the report!!
