### ISSUE TITLE
Not reading file

### ISSUE THREAD

**Issue by Dan-Burns** [getcontacts/getcontacts#70]
Hello,

I've run several xtc files but for some reason, one won't work.  I have reprocessed the trajectory to make sure it is not some error there but I continue to get this error.

Thank you,
Dan

Traceback (most recent call last):
  File "/work/07303/tg866027/getcontacts/get_dynamic_contacts.py", line 97, in <module>
    main()
  File "/work/07303/tg866027/getcontacts/get_dynamic_contacts.py", line 80, in main
    compute_contacts(top, traj, output, itypes, geom_criteria, cores, beg, end, stride, distout,
  File "/work/07303/tg866027/getcontacts/contact_calc/compute_contacts.py", line 226, in compute_contacts
    index_to_atom = gen_index_to_atom(top, traj)
  File "/work/07303/tg866027/getcontacts/contact_calc/contact_utils.py", line 234, in gen_index_to_atom
    trajid = load_traj(top, traj, 0, 1, 1)
  File "/work/07303/tg866027/getcontacts/contact_calc/contact_utils.py", line 108, in load_traj
    molecule.read(trajid, traj_file_type, traj, beg=beg_frame, end=end_frame, skip=stride, waitfor=-1)
RuntimeError: Unable to read filename 'teeic_sep.xtc' format 'xtc'
usage: get_contact_frequencies.py [-h] --input_files FILE.tsv [FILE.tsv ...]
                                  [--label_file FILE.tsv] --output_file
                                  FILE.tsv [--itypes ITYPE [ITYPE ...]]

**Comment by RasmusFonseca** [comment]
What is the command you run to get this error?

**Comment by Dan-Burns** [comment]
Hi Rasmus,

get_dynamic_contacts.py --topology teeic_sep.pdb --trajectory teeic_sep.xtc --output teeic_sep_loop_cont.tsv --cores 48 --sele "protein" --sele2 "resname SEP" --itypes all --distout

Thank you,

Dan

**Comment by RasmusFonseca** [comment]
Thanks, the usage directions there look wrong (`usage: get_contact_frequencies.py`), so I'll need to look into that. Are you normally able to load this trajectory in VMD?

**Comment by RasmusFonseca** [comment]
Does it work if you `catdcd -o teeic_sep.dcd -i teeic_sep.pdb teeic_sep.xtc` first?

http://www.ks.uiuc.edu/Research/vmd/plugins/catdcd/

**Comment by Dan-Burns** [comment]
Turns out it was an issue with my structure file but the error was only indicating the xtc file.  My atom numbers weren't matching between the two files.

Thank you for your help!
Dan

**Comment by RasmusFonseca** [comment]
Thanks for following up! I'll make a note to see if we can make a better error message 😁
